import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distDir = path.join(__dirname, 'dist');
const htmlPath = path.join(distDir, 'index.html');

try {
  if (!fs.existsSync(htmlPath)) {
    console.error(`index.html not found at: ${htmlPath}`);
    process.exit(1);
  }

  let html = fs.readFileSync(htmlPath, 'utf8');

  // Regex to match any local CSS link tags generated by Vite (matching /assets/*.css)
  const cssRegex = /<link rel="stylesheet"[^>]*href="\/assets\/([^"]+)\.css"[^>]*>/g;
  let match;
  const matches = [];
  while ((match = cssRegex.exec(html)) !== null) {
    matches.push({
      fullTag: match[0],
      filename: `${match[1]}.css`
    });
  }

  for (const item of matches) {
    const cssPath = path.join(distDir, 'assets', item.filename);

    if (fs.existsSync(cssPath)) {
      console.log(`Inlining CSS: ${item.filename} (${(fs.statSync(cssPath).size / 1024).toFixed(1)} KB)`);
      let cssContent = fs.readFileSync(cssPath, 'utf8');

      // Optimize font display properties to swap/optional for PageSpeed compliance
      cssContent = cssContent.replace(/font-display\s*:\s*block/g, 'font-display: swap');

      // Replace stylesheet link with inline <style> block
      const styleTag = `<style>${cssContent}</style>`;
      html = html.replace(item.fullTag, styleTag);

      // Clean up the external stylesheet file
      fs.unlinkSync(cssPath);
      console.log(`Deleted external CSS file: ${item.filename}`);
    } else {
      console.error(`CSS file not found at: ${cssPath}`);
    }
  }

  if (matches.length > 0) {
    fs.writeFileSync(htmlPath, html, 'utf8');
    console.log(`Successfully inlined ${matches.length} CSS files into dist/index.html`);
  } else {
    console.log('No generated stylesheet link tags found in index.html to inline.');
  }
} catch (err) {
  console.error('Failed to inline CSS:', err);
  process.exit(1);
}
