import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distDir = path.join(__dirname, 'dist');
const htmlPath = path.join(distDir, 'index.html');

try {
  if (!fs.existsSync(htmlPath)) {
    console.error(`index.html not found at: ${htmlPath}`);
    process.exit(1);
  }

  let html = fs.readFileSync(htmlPath, 'utf8');

  // Regex to match the CSS link tag generated by Vite
  const cssRegex = /<link rel="stylesheet"[^>]*href="\/assets\/index-([^"]+)\.css"[^>]*>/;
  const match = html.match(cssRegex);

  if (match) {
    const fullTag = match[0];
    const hash = match[1];
    const cssFilename = `index-${hash}.css`;
    const cssPath = path.join(distDir, 'assets', cssFilename);

    if (fs.existsSync(cssPath)) {
      console.log(`Inlining CSS: ${cssFilename} (${(fs.statSync(cssPath).size / 1024).toFixed(1)} KB)`);
      let cssContent = fs.readFileSync(cssPath, 'utf8');

      // Optimize font display properties to swap/optional for PageSpeed compliance
      cssContent = cssContent.replace(/font-display\s*:\s*block/g, 'font-display: swap');

      // Replace stylesheet link with inline <style> block
      const styleTag = `<style>${cssContent}</style>`;
      html = html.replace(fullTag, styleTag);

      fs.writeFileSync(htmlPath, html, 'utf8');
      console.log('Successfully inlined CSS into dist/index.html');

      // Clean up the external stylesheet file
      fs.unlinkSync(cssPath);
      console.log(`Deleted external CSS file: ${cssFilename}`);
    } else {
      console.error(`CSS file not found at: ${cssPath}`);
    }
  } else {
    console.log('No generated stylesheet link tag found in index.html to inline.');
  }
} catch (err) {
  console.error('Failed to inline CSS:', err);
  process.exit(1);
}
